"""Generating every reported number from artifacts.

Tables become ``\\input`` targets and inline numbers become generated macros, so a
number cannot drift from the run that produced it. This module only turns manifests and
records into tables; :func:`qomlaq.pipeline.report` finds them on disk.

Two rules are enforced here rather than remembered:

* a contaminated record (one scored on data its model trained on) never reaches a
  headline table;
* the metric column header is :attr:`~qomlaq.metrics.PRIMARY`'s derived display name,
  so relabeling the metric is impossible without changing the metric.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Iterable, Mapping, Sequence

import pandas as pd

from .config import DIRECTIONS, config_has_verses
from .evaluate import EvalRecord
from .metrics import PRIMARY, SECONDARY

_LATEX_ESCAPES = {"&": r"\&", "%": r"\%", "$": r"\$", "#": r"\#", "_": r"\_"}
_GENERATED = "% Generated by qomlaq.report -- do not edit by hand."


def _escape(text: object) -> str:
    out = str(text)
    for char, replacement in _LATEX_ESCAPES.items():
        out = out.replace(char, replacement)
    return out


def _fmt(value: object, decimals: int = 2) -> str:
    if isinstance(value, float):
        return f"{value:.{decimals}f}"
    if isinstance(value, int):
        return f"{value:,}"
    return _escape(value)


def to_latex(frame: pd.DataFrame, *, caption: str, label: str, align: str | None = None) -> str:
    """A booktabs table. Deliberately plain: this file is generated, never hand-edited."""
    align = align or ("l" * 1 + "r" * (len(frame.columns) - 1))
    header = " & ".join(rf"\textbf{{{_escape(c)}}}" for c in frame.columns) + r" \\"
    body = "\n".join(
        " & ".join(_fmt(v) for v in row) + r" \\" for row in frame.itertuples(index=False)
    )
    return "\n".join(
        [
            _GENERATED,
            r"\begin{table}[t]",
            r"  \centering",
            r"  \small",
            rf"  \begin{{tabular}}{{{align}}}",
            r"    \toprule",
            f"    {header}",
            r"    \midrule",
            *(f"    {line}" for line in body.splitlines()),
            r"    \bottomrule",
            r"  \end{tabular}",
            rf"  \caption{{{caption}}}",
            rf"  \label{{{label}}}",
            r"\end{table}",
            "",
        ]
    )


def _direction_label(direction: str) -> str:
    return DIRECTIONS[direction].label


# ---------------------------------------------------------------------------- corpus


def corpus_table(manifest: dict) -> pd.DataFrame:
    """One row per source, then one total per corpus configuration."""
    rows = []
    for source in manifest["sources"]:
        rows.append(
            {
                "Source": source["name"],
                "Segments": source["after_qc"],
                "Lines": source["lines"],
                "Titles": source["titles"],
                "Units": source["groups"],
                "Qom tokens": source["qom_tokens"],
                "ES tokens": source["es_tokens"],
                "Qom len": f"{source['qom_len_mean']:.2f} ± {source['qom_len_std']:.2f}",
                "ES len": f"{source['es_len_mean']:.2f} ± {source['es_len_std']:.2f}",
            }
        )
    frame = pd.DataFrame(rows)
    totals = []
    for config in manifest["configs"]:
        members = [s["name"] for s in manifest["sources"] if config in s["configs"]]
        chunk = frame[frame["Source"].isin(members)]
        totals.append(
            {
                "Source": f"Total ({config})",
                "Segments": manifest["counts"][f"{config}_rows"],
                "Lines": int(chunk["Lines"].sum()),
                "Titles": int(chunk["Titles"].sum()),
                "Units": int(chunk["Units"].sum()),
                "Qom tokens": int(chunk["Qom tokens"].sum()),
                "ES tokens": int(chunk["ES tokens"].sum()),
                "Qom len": "",
                "ES len": "",
            }
        )
    return pd.concat([frame, pd.DataFrame(totals)], ignore_index=True)


# ---------------------------------------------------------------------------- splits


def split_table(manifests: Sequence[dict], *, include_controls: bool = False) -> pd.DataFrame:
    rows = []
    for manifest in manifests:
        if manifest.get("purpose", "headline") != "headline" and not include_controls:
            continue
        realized = manifest["realized"]
        rows.append(
            {
                "Config": manifest["config"],
                "Split": manifest["strategy"],
                "Bible unit": (
                    manifest["bible_grouping"] if config_has_verses(manifest["config"]) else "-"
                ),
                "Train": realized["train"]["rows"],
                "Dev": realized["dev"]["rows"],
                "Test": realized["test"]["rows"],
                "Test %": round(100 * realized["test"]["fraction"], 1),
                "Units": sum(realized[p]["groups"] for p in ("train", "dev", "test")),
            }
        )
    return pd.DataFrame(rows).sort_values(["Config", "Split"], kind="mergesort").reset_index(drop=True)


# --------------------------------------------------------------------------- results


def results_table(records: Iterable[EvalRecord], *, allow_contaminated: bool = False) -> pd.DataFrame:
    rows = []
    skipped = []
    for record in records:
        if record.contaminated and not allow_contaminated:
            skipped.append(record.run_id)
            continue
        card = record.model_card
        row = {
            "Config": card["config"],
            "Direction": _direction_label(card["direction"]),
            "Split": card["strategy"],
            "n": record.n_pairs,
        }
        for spec in (PRIMARY, *SECONDARY):
            row[spec.display_name] = record.scores.get(spec.display_name)
        rows.append(row)
    if skipped:
        print(f"  excluded {len(skipped)} contaminated record(s) from the table: {skipped}")
    return pd.DataFrame(rows)


def ablation_table(records: Iterable[EvalRecord]) -> pd.DataFrame:
    """Several models on one shared, verifiably held-out set."""
    records = list(records)
    split_ids = {r.split_id for r in records}
    if len(split_ids) > 1:
        raise ValueError(
            f"an ablation must share one evaluation set, got {sorted(split_ids)}; "
            "scores computed on different test sets are not comparable."
        )
    contaminated = [r.run_id for r in records if r.contaminated]
    if contaminated:
        raise ValueError(
            f"refusing to build an ablation from contaminated records: {contaminated}"
        )
    rows = []
    for record in records:
        rows.append(
            {
                "Experiment": record.experiment or record.model_card.get("experiment", ""),
                "Model": record.model_card["config"],
                "Direction": _direction_label(record.model_card["direction"]),
                PRIMARY.display_name: record.scores.get(PRIMARY.display_name),
                "n": record.n_pairs,
            }
        )
    return pd.DataFrame(rows)


def per_source_table(record: EvalRecord) -> pd.DataFrame:
    """What a single corpus-level score is hiding."""
    return (
        pd.DataFrame(
            [{"Source": k, PRIMARY.display_name: v} for k, v in sorted(record.per_source.items())]
        )
        .sort_values(PRIMARY.display_name, ascending=False)
        .reset_index(drop=True)
    )


def metric_signatures(records: Iterable[EvalRecord]) -> pd.DataFrame:
    seen: dict[str, str] = {}
    for record in records:
        seen.update(record.signatures)
    return pd.DataFrame(
        [{"Metric": name, "sacrebleu signature": sig} for name, sig in sorted(seen.items())]
    )


# ------------------------------------------------------------------------- assembly


def _macro_name(*parts: str) -> str:
    """LaTeX macro names may only contain letters."""
    words = "".join(p.title().replace("_", "").replace("-", "") for p in parts)
    return "".join(ch for ch in words if ch.isalpha())


def latex_macros(corpus_manifest: dict, split_manifests: Sequence[dict],
                 records: Sequence[EvalRecord]) -> str:
    """Inline numbers as macros, so prose cannot drift from the artifacts."""
    counts = corpus_manifest["counts"]
    lines = [_GENERATED]
    lines.append(rf"\newcommand{{\CorpusSegments}}{{{counts['rows']:,}}}")
    lines.append(rf"\newcommand{{\CorpusUnits}}{{{counts['groups']:,}}}")
    lines.append(rf"\newcommand{{\CorpusSha}}{{{corpus_manifest['corpus_sha256'][:8]}}}")
    lines.append(rf"\newcommand{{\PrimaryMetric}}{{{PRIMARY.display_name}}}")
    for config in corpus_manifest["configs"]:
        value = counts[f"{config}_rows"]
        lines.append(rf"\newcommand{{\Segments{_macro_name(config)}}}{{{value:,}}}")

    for manifest in split_manifests:
        if manifest.get("purpose", "headline") != "headline":
            continue
        base = _macro_name(manifest["config"], manifest["strategy"])
        for partition in ("train", "dev", "test"):
            value = manifest["realized"][partition]["rows"]
            lines.append(rf"\newcommand{{\Split{base}{partition.title()}}}{{{value:,}}}")

    for record in records:
        if record.contaminated:
            continue
        card = record.model_card
        base = _macro_name(card["config"], card["strategy"], card["direction"])
        value = record.scores.get(PRIMARY.display_name)
        if value is not None:
            lines.append(rf"\newcommand{{\Score{base}}}{{{value:.2f}}}")
    return "\n".join(lines) + "\n"


def write_tables(
    out_dir: str | Path,
    *,
    experiment: str,
    corpus_manifest: dict,
    split_manifests: Sequence[dict],
    records: Sequence[EvalRecord],
    evaluations: Mapping[str, Sequence[EvalRecord]],
) -> dict[str, Path]:
    """Write every table and macro file for one experiment. Idempotent."""
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    written: dict[str, Path] = {}
    corpus_sha8 = corpus_manifest["corpus_sha256"][:8]

    def emit(name: str, frame: pd.DataFrame, *, caption: str, label: str,
             align: str | None = None) -> None:
        (out_dir / f"{name}.tex").write_text(
            to_latex(frame, caption=caption, label=label, align=align), encoding="utf-8"
        )
        frame.to_csv(out_dir / f"{name}.csv", index=False)
        written[name] = out_dir / f"{name}.tex"

    emit(
        "table1_corpus",
        corpus_table(corpus_manifest),
        caption=(
            "QomL'aqtaqa corpus after filtering. Segment counts are post-QC and include "
            "chapter, section and fragment title pairs, listed separately. "
            f"Corpus hash \\texttt{{{corpus_sha8}}}."
        ),
        label="tab:corpus-stats",
    )

    forced = sorted({s for m in split_manifests for s in m.get("forced_partitions", {})})
    emit(
        "table2_splits",
        split_table(split_manifests),
        caption=(
            "Dataset splits. Partitions are disjoint at the discourse-unit level; "
            "Bible verses are grouped by book and chapter. "
            + (f"{', '.join(forced)} is held out entirely as an out-of-domain probe."
               if forced else "")
        ),
        label="tab:splits",
    )

    everything = [*records, *(r for rs in evaluations.values() for r in rs)]
    if records:
        emit(
            "table3_results",
            results_table(records),
            caption=(
                f"MT results. Primary metric is {PRIMARY.display_name} "
                "(sacrebleu; see Table~\\ref{tab:metric-signatures})."
            ),
            label="tab:results",
        )
    for name, evaluation_records in evaluations.items():
        if evaluation_records:
            emit(
                f"evaluation_{name}",
                ablation_table(evaluation_records),
                caption=f"Evaluation {_escape(name)}: several models on one shared test set.",
                label=f"tab:evaluation-{name}",
            )
    if everything:
        emit(
            "metric_signatures",
            metric_signatures(everything),
            caption="Exact sacrebleu parameterization of every reported metric.",
            label="tab:metric-signatures",
            align="ll",
        )

    (out_dir / "macros.tex").write_text(
        latex_macros(corpus_manifest, split_manifests, records), encoding="utf-8"
    )
    written["macros"] = out_dir / "macros.tex"

    summary = {
        "experiment": experiment,
        "corpus": corpus_manifest.get("corpus"),
        "corpus_sha256": corpus_manifest["corpus_sha256"],
        "primary_metric": PRIMARY.display_name,
        "splits": {m["split_id"]: m["split_sha256"] for m in split_manifests},
        "records": [r.summary_row() for r in records],
        "evaluations": {
            name: [r.summary_row() for r in rs] for name, rs in evaluations.items()
        },
    }
    (out_dir / "numbers.json").write_text(
        json.dumps(summary, indent=2, ensure_ascii=False), encoding="utf-8"
    )
    written["numbers"] = out_dir / "numbers.json"
    return written
